import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const text = {
  en: { demo:'DEMO MODE · Fictional household data', employer:'Employer', helper:'Helper', today:'Today', planner:'Planner', issues:'Issues', greeting:'Good morning, Alex', completed:'Completed', pending:'Pending', help:'Need help', progress:'Today’s progress', timeline:'Today’s timeline', schedule:'Schedule', restDay:'Rest day', leave:'Annual leave', holiday:'Holiday', addTask:'Add task template', edit:'Edit', delete:'Delete', save:'Save', cancel:'Cancel', reset:'Reset demo data', resolve:'Mark resolved', reportIssue:'Report an issue', description:'Short description', category:'Category', time:'Time', title:'Task title', status:'Status', taskTemplate:'Weekly task templates', noTasks:'No tasks planned — enjoy the rest day.', pendingStatus:'Pending', inProgressStatus:'In progress', completedStatus:'Completed', needHelpStatus:'Need help', skippedStatus:'Skipped', missing:'Missing supplies', cannot:'Cannot complete', other:'Other', local:'Local demo only — no account, Firebase or cross-device sync yet.', planned:'Planning target only', dateChanges:'Dates & exceptions', addDate:'Add date change', type:'Type', date:'Date', comment:'Comment', noIssues:'No open issues today.', restDays:'Weekly rest days', sun:'Sun', mon:'Mon', tue:'Tue', wed:'Wed', thu:'Thu', fri:'Fri', sat:'Sat' },
  zh: { demo:'示範模式 · 全部為虛構家庭資料', employer:'僱主', helper:'工人姐姐', today:'今天', planner:'計劃', issues:'問題', greeting:'早晨，Alex', completed:'已完成', pending:'待處理', help:'需要協助', progress:'今日進度', timeline:'今日時間表', schedule:'日程', restDay:'休息日', leave:'年假', holiday:'假期', addTask:'新增工作範本', edit:'編輯', delete:'刪除', save:'儲存', cancel:'取消', reset:'重設示範資料', resolve:'標記已解決', reportIssue:'回報問題', description:'簡短說明', category:'類別', time:'時間', title:'工作名稱', status:'狀態', taskTemplate:'每週工作範本', noTasks:'今天沒有安排工作，好好享受休息日。', pendingStatus:'待處理', inProgressStatus:'進行中', completedStatus:'已完成', needHelpStatus:'需要協助', skippedStatus:'已略過', missing:'缺少用品', cannot:'未能完成', other:'其他', local:'只限本地示範：尚未有帳戶、Firebase 或跨裝置同步。', planned:'只作工作規劃參考', dateChanges:'日期及例外安排', addDate:'新增日期安排', type:'類型', date:'日期', comment:'備註', noIssues:'今天沒有未解決問題。', restDays:'每週休息日', sun:'日', mon:'一', tue:'二', wed:'三', thu:'四', fri:'五', sat:'六' },
}
const days = ['sun','mon','tue','wed','thu','fri','sat']
const seed = { tasks:[
  {id:'breakfast',time:'08:00',en:'Prepare breakfast',zh:'準備早餐',descEn:'Breakfast for the household',descZh:'為家庭準備早餐',status:'completed',completedAt:'08:18'},
  {id:'laundry',time:'10:00',en:'Laundry and bedding',zh:'洗衫及床單',descEn:'Wash, dry and fold light items',descZh:'清洗、晾曬及摺疊輕便衣物',status:'inProgress',completedAt:''},
  {id:'lunch',time:'12:00',en:'Prepare lunch',zh:'準備午餐',descEn:'Simple family lunch',descZh:'準備簡單家庭午餐',status:'pending',completedAt:''},
  {id:'supplies',time:'16:00',en:'Check cleaning supplies',zh:'檢查清潔用品',descEn:'Check detergent and kitchen towels',descZh:'檢查洗衣液及廚房紙',status:'needHelp',completedAt:''}
], templates:[
  {id:'t1',days:[1,2,3,4,5],time:'08:00',en:'Prepare breakfast',zh:'準備早餐'}, {id:'t2',days:[1],time:'10:00',en:'Laundry and bedding',zh:'洗衫及床單'}, {id:'t3',days:[3],time:'10:00',en:'Clean refrigerator',zh:'清潔雪櫃'}
], restDays:[0], exceptions:[{id:'e1',date:'2026-10-01',type:'holiday',note:'National Day'}], issues:[{id:'i1',category:'missing',en:'Only one kitchen towel left.',zh:'廚房紙只剩下一卷。',resolved:false,time:'09:20'}] }
const copy = x => JSON.parse(JSON.stringify(x))
const statusKey = { pending:'pendingStatus', inProgress:'inProgressStatus', completed:'completedStatus', needHelp:'needHelpStatus', skipped:'skippedStatus' }

function App() {
  const [lang,setLang] = useState(() => localStorage.getItem('hh-lang') || 'en')
  const [role,setRole] = useState('employer'), [view,setView] = useState('home')
  const [data,setData] = useState(() => JSON.parse(localStorage.getItem('hh-demo') || 'null') || copy(seed))
  const t = text[lang], employer = role === 'employer'
  useEffect(() => localStorage.setItem('hh-lang',lang),[lang]); useEffect(() => localStorage.setItem('hh-demo',JSON.stringify(data)),[data])
  const active = data.tasks.filter(x => x.status !== 'skipped'), done = active.filter(x => x.status === 'completed').length
  const stats = { done, pending:active.filter(x=>['pending','inProgress'].includes(x.status)).length, help:active.filter(x=>x.status==='needHelp').length, percent:active.length ? Math.round(done/active.length*100):0 }
  const localDate = new Date().toLocaleDateString('en-CA')
  const restToday = data.restDays.includes(new Date().getDay()) || data.exceptions.some(x => x.date === localDate && ['restDay','holiday','leave'].includes(x.type))
  const updateStatus = (id,status) => setData(d=>({...d,tasks:d.tasks.map(x=>x.id===id?{...x,status,completedAt:status==='completed'?new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):x.completedAt}:x)}))
  const reset = () => { if(confirm('Reset fictional demo data?')) { setData(copy(seed)); setView('home') } }
  return <div className="shell"><header><div className="brand"><span>✦</span><b>Home Helper</b></div><div><button className="lang" onClick={()=>setLang(lang==='en'?'zh':'en')}>{lang==='en'?'繁':'EN'}</button><button className="role" onClick={()=>setRole(employer?'helper':'employer')}>{employer?t.employer:t.helper}</button></div></header><main>
    <div className="demo">● {t.demo}</div>
    {view==='home'&&<Dashboard {...{t,lang,role,data,stats,updateStatus,setView,restToday}}/>}
    {view==='planner'&&<Planner {...{t,lang,data,setData,employer}}/>}
    {view==='issues'&&<Issues {...{t,lang,data,setData,employer}}/>}
  </main><nav><Nav icon="⌂" label={t.today} active={view==='home'} onClick={()=>setView('home')}/><Nav icon="▦" label={t.planner} active={view==='planner'} onClick={()=>setView('planner')}/><Nav icon="!" label={t.issues} active={view==='issues'} onClick={()=>setView('issues')} badge={data.issues.filter(x=>!x.resolved).length}/></nav><footer><span>{t.local}</span><button onClick={reset}>{t.reset}</button></footer></div>
}
function Nav({icon,label,active,onClick,badge}) { return <button className={active?'active':''} onClick={onClick}><b>{icon}</b>{badge>0&&<i>{badge}</i>}<small>{label}</small></button> }
function Dashboard({t,lang,role,data,stats,updateStatus,setView,restToday}) { const date=new Intl.DateTimeFormat(lang==='zh'?'zh-HK':'en-GB',{weekday:'long',month:'long',day:'numeric'}).format(new Date()); const helper=role==='helper'; return <><section className="hero"><p>{date}</p><h1>{helper?(lang==='zh'?'你好，May':'Hello, May'):t.greeting}</h1><small>{t.planned}</small></section>{restToday?<section className="rest"><b>☀</b><div><strong>{t.restDay}</strong><p>{t.noTasks}</p></div></section>:<><section className="progress"><div className="ring" style={{'--p':`${stats.percent*3.6}deg`}}><div><b>{stats.percent}%</b><small>{t.completed}</small></div></div><div><p>{t.progress}</p><h2>{stats.done} / {data.tasks.length} {t.completed.toLowerCase()}</h2><span><b>{stats.pending}</b> {t.pending} &nbsp; <b className={stats.help?'orange':''}>{stats.help}</b> {t.help}</span></div></section><section className="heading"><div><p>{t.schedule}</p><h2>{t.timeline}</h2></div>{helper&&<button className="link" onClick={()=>setView('issues')}>{t.reportIssue} +</button>}</section><div className="tasks">{data.tasks.map(task=><Task key={task.id} {...{task,t,lang,helper,updateStatus}}/>)}</div></>}</> }
function Task({task,t,lang,helper,updateStatus}) { const next={pending:'inProgress',inProgress:'completed',completed:'pending',needHelp:'inProgress'}[task.status]; return <article className={'task '+task.status}><b className="time">{task.time}</b><div><div className="tasktop"><h3>{task[lang]}</h3><span>{t[statusKey[task.status]]}</span></div><p>{lang==='zh'?task.descZh:task.descEn}</p>{task.completedAt&&<small>✓ {t.completed} · {task.completedAt}</small>}</div>{helper&&<button className="tick" onClick={()=>updateStatus(task.id,next)}>{task.status==='completed'?'↺':task.status==='needHelp'?'?':'✓'}</button>}</article> }
function Planner({t,lang,data,setData,employer}) { const [edit,setEdit]=useState(null),[date,setDate]=useState(false); const remove=id=>setData(d=>({...d,templates:d.templates.filter(x=>x.id!==id)})); const toggle=d=>setData(x=>({...x,restDays:x.restDays.includes(d)?x.restDays.filter(v=>v!==d):[...x.restDays,d]})); return <><section className="page"><p>{t.schedule}</p><h1>{t.planner}</h1><span>{employer?(lang==='zh'?'設定重複工作、休息日與特別安排。':'Set recurring work, rest days and special arrangements.'):(lang==='zh'?'查看本週工作和休息安排。':'Review weekly work and rest arrangements.')}</span></section><section className="panel"><div className="heading"><h2>{t.taskTemplate}</h2>{employer&&<button className="primary small" onClick={()=>setEdit({days:[1],time:'09:00',en:'',zh:''})}>+ {t.addTask}</button>}</div>{data.templates.map(x=><div className="template" key={x.id}><b>{x.time}</b><div><strong>{x[lang]}</strong><small>{x.days.map(d=>t[days[d]]).join(' · ')}</small></div>{employer&&<aside><button onClick={()=>setEdit(x)}>{t.edit}</button><button onClick={()=>remove(x.id)}>{t.delete}</button></aside>}</div>)}</section><section className="panel"><h2>{t.restDays}</h2><div className="week">{days.map((d,i)=><button disabled={!employer} className={data.restDays.includes(i)?'selected':''} onClick={()=>toggle(i)} key={d}>{t[d]}</button>)}</div></section><section className="panel"><div className="heading"><h2>{t.dateChanges}</h2>{employer&&<button className="primary small" onClick={()=>setDate(true)}>+ {t.addDate}</button>}</div>{data.exceptions.map(x=><div className="exception" key={x.id}><span>{x.date}</span><b>{t[x.type]}</b><small>{x.note}</small>{employer&&<button onClick={()=>setData(d=>({...d,exceptions:d.exceptions.filter(e=>e.id!==x.id)}))}>×</button>}</div>)}</section>{edit&&<TemplateModal {...{t,edit,setEdit,setData}}/>}{date&&<DateModal {...{t,setDate,setData}}/>}</> }
function TemplateModal({t,edit,setEdit,setData}) { const [form,setForm]=useState(edit); const save=e=>{e.preventDefault();if(!form.en||!form.zh)return;setData(d=>({...d,templates:d.templates.some(x=>x.id===form.id)?d.templates.map(x=>x.id===form.id?form:x):[...d.templates,{...form,id:'t'+Date.now()}]}));setEdit(null)};return <Modal><form onSubmit={save}><h2>{edit.id?t.edit:t.addTask}</h2><label>{t.title} (EN)<input required value={form.en} onChange={e=>setForm({...form,en:e.target.value})}/></label><label>{t.title} (繁中)<input required value={form.zh} onChange={e=>setForm({...form,zh:e.target.value})}/></label><div className="formgrid"><label>{t.time}<input type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label><label>{t.schedule}<select value={form.days[0]} onChange={e=>setForm({...form,days:[+e.target.value]})}>{days.map((d,i)=><option value={i} key={d}>{t[d]}</option>)}</select></label></div><Actions {...{t,close:()=>setEdit(null)}}/></form></Modal> }
function DateModal({t,setDate,setData}) { const [form,setForm]=useState({date:'',type:'holiday',note:''}); const save=e=>{e.preventDefault();setData(d=>({...d,exceptions:[...d.exceptions,{...form,id:'e'+Date.now()}]}));setDate(false)};return <Modal><form onSubmit={save}><h2>{t.addDate}</h2><label>{t.date}<input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>{t.type}<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="restDay">{t.restDay}</option><option value="holiday">{t.holiday}</option><option value="leave">{t.leave}</option></select></label><label>{t.comment}<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><Actions {...{t,close:()=>setDate(false)}}/></form></Modal> }
function Modal({children}) { return <div className="shade"><div className="modal">{children}</div></div> } function Actions({t,close}) { return <div className="actions"><button type="button" onClick={close}>{t.cancel}</button><button className="primary">{t.save}</button></div> }
function Issues({t,lang,data,setData,employer}) { const [open,setOpen]=useState(false),[form,setForm]=useState({category:'needHelp',note:''});const save=e=>{e.preventDefault();if(!form.note)return;setData(d=>({...d,issues:[{id:'i'+Date.now(),category:form.category,en:form.note,zh:form.note,resolved:false,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),},...d.issues]}));setOpen(false);setForm({category:'needHelp',note:''})}; const shown=data.issues.filter(x=>employer||!x.resolved);return <><section className="page"><p>{t.help}</p><h1>{t.issues}</h1><span>{lang==='zh'?'有需要時，請隨時提出；這不是表現評分。':'Raise a concern whenever needed — this is not a performance score.'}</span>{!employer&&<button className="primary report" onClick={()=>setOpen(true)}>+ {t.reportIssue}</button>}</section><div className="issue-list">{shown.length?shown.map(x=><article className={'issue '+(x.resolved?'resolved':'')} key={x.id}><i>{x.category==='missing'?'▣':x.category==='needHelp'?'?':'!'}</i><div><b>{t[x.category]}</b><p>{x[lang]}</p><small>{x.time}{x.resolved&&' · ✓'}</small></div>{employer&&!x.resolved&&<button onClick={()=>setData(d=>({...d,issues:d.issues.map(i=>i.id===x.id?{...i,resolved:true}:i)}))}>{t.resolve}</button>}</article>):<div className="empty">✓ {t.noIssues}</div>}</div>{open&&<Modal><form onSubmit={save}><h2>{t.reportIssue}</h2><label>{t.category}<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="needHelp">{t.help}</option><option value="missing">{t.missing}</option><option value="cannot">{t.cannot}</option><option value="other">{t.other}</option></select></label><label>{t.description}<textarea required maxLength="160" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><Actions {...{t,close:()=>setOpen(false)}}/></form></Modal>}</> }
createRoot(document.getElementById('root')).render(<App />)
